### ISSUE TITLE
Gym Badges - Make it possible to hide Gyms with Gold Badges

### ISSUE THREAD

**Issue by spammer23** [WatWowMap/ReactMap#657] opened 2023-02-10 15:13 UTC
At the moment the filter shows the selected Badge level, but you can't select Bronze and silver to exclude Golden Badges.

**Comment by clburlison** [comment] 2023-06-15 23:20
Duplicate of #541. Feel free to go 👍 that issue

**Closed by clburlison** 2023-06-15 23:20 UTC
Labels: Duplicate
